### ISSUE TITLE
支持RSS订阅吗

### ISSUE THREAD

**Issue by ofexe** [sbabybird/MachineDigest#1]
因为习惯使用电脑查看。现在微信订阅打开的也没有用浏览器打开的选项，视窗很小，看起来不是很方便。
请问有没有RSS的订阅源

**Comment by sbabybird** [comment]
暂时还不能支持 rss 订阅，可以先尝试通过 “竹白” 在邮箱里订阅 newsletter。

地址为：https://niupitools.zhubai.love/

**Comment by sbabybird** [comment]
暂时还不能支持 rss 订阅，可以先尝试通过 “竹白” 在邮箱里订阅 newsletter。

地址为：https://niupitools.zhubai.love/
